// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "white": "rgba(255, 255, 255, 1)",
 "black": "rgba(34, 34, 34, 1)"
}

module.exports = colors;