// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 "bold": "Roboto-Bold",
 "medium": "Roboto-Medium",
 "regular": null,
 "light": "Roboto-Light"
}

module.exports = fontFamilies;